// AUTO-GENERATED by generate_regions.py -- do not hand-edit.
// Region tags, nonlinear iron B-H curve, and winding current-density
// sources for the real BPL-700 assembly. See generate_regions.py for
// derivation.

Group {
  Air = Region[1];
  Iron = Region[2];
  Winding0 = Region[3];
  Winding1 = Region[4];
  Winding2 = Region[5];
  Winding3 = Region[6];
  Winding4 = Region[7];
  OuterBnd = Region[8];
  Windings = Region[{Winding0, Winding1, Winding2, Winding3, Winding4}];
  DomainC  = Region[{Windings}];
  DomainCC = Region[{Air, Iron}];
  Domain   = Region[{DomainC, DomainCC}];
}

Function {
  mu0 = 1.2566370614359173e-06;

  // Iron B-H curve. The hardware is ASTM A36; these are AISI 1008
  // points used as a PROXY -- see generate_regions.py for why, which
  // way the error runs, and its rough size.
  AISI1008_H() = {0.0, 159.2, 318.3, 477.5, 636.6, 795.8, 1591.5, 3183.1, 4774.6, 6366.2, 7957.7, 15915.5, 31831.0, 47746.5, 63662.0, 79577.5, 159155.0, 318310.0, 397887.0};
  AISI1008_B() = {0.0, 0.2402, 0.8654, 1.1106, 1.2458, 1.331, 1.5, 1.6, 1.683, 1.741, 1.78, 1.905, 2.025, 2.085, 2.13, 2.165, 2.28, 2.485, 2.585};
  AISI1008_B2() = AISI1008_B()^2;
  AISI1008_nu_list() = AISI1008_H() / AISI1008_B();
  AISI1008_nu_list(0) = AISI1008_nu_list(1);  // avoid 0/0 at B=0
  AISI1008_nu_b2_list() = ListAlt[AISI1008_B2(), AISI1008_nu_list()];
  AISI1008_nu[] = InterpolationLinear[SquNorm[$1]]{AISI1008_nu_b2_list()};

  nu[Air]  = 1 / mu0;
  nu[Iron] = AISI1008_nu[$1];  // nonlinear -- see magnetostatics_assembly.pro
                                   // for the Vol_L_Mag/Vol_NL_Mag Galerkin split this requires
  nu[Windings] = 1 / mu0;  // copper, non-magnetic

  // Winding0: pole=inner_coil turns=260 I=1.3A A_cross=2.447257e-04 polarity=-1 -> Jmag=-1.381138e+06 A/m^2
  Js[Winding0] = $IFrac * (-1381138.0561832997 / Sqrt[(X[]-(-0.00016711298290286914))^2 + (Z[]-(-6.158486390058627e-16))^2]) * Vector[(Z[]-(-6.158486390058627e-16)), 0, -(X[]-(-0.00016711298290286914))];
  // Winding1: pole=outer_coil turns=165 I=1.3A A_cross=3.262948e-04 polarity=+1 -> Jmag=6.573810e+05 A/m^2
  Js[Winding1] = $IFrac * (657380.9891518643 / Sqrt[(X[]-(0.04427401054092428))^2 + (Z[]-(-0.044450000000004763))^2]) * Vector[(Z[]-(-0.044450000000004763)), 0, -(X[]-(0.04427401054092428))];
  // Winding2: pole=outer_coil turns=165 I=1.3A A_cross=3.262948e-04 polarity=+1 -> Jmag=6.573810e+05 A/m^2
  Js[Winding2] = $IFrac * (657380.9891518643 / Sqrt[(X[]-(-0.04462598945906393))^2 + (Z[]-(0.04444999999997634))^2]) * Vector[(Z[]-(0.04444999999997634)), 0, -(X[]-(-0.04462598945906393))];
  // Winding3: pole=outer_coil turns=165 I=1.3A A_cross=3.262948e-04 polarity=+1 -> Jmag=6.573810e+05 A/m^2
  Js[Winding3] = $IFrac * (657380.9891518643 / Sqrt[(X[]-(-0.04462598945904972))^2 + (Z[]-(-0.04444999999999766))^2]) * Vector[(Z[]-(-0.04444999999999766)), 0, -(X[]-(-0.04462598945904972))];
  // Winding4: pole=outer_coil turns=165 I=1.3A A_cross=3.262948e-04 polarity=+1 -> Jmag=6.573810e+05 A/m^2
  Js[Winding4] = $IFrac * (657380.9891518643 / Sqrt[(X[]-(0.04427401054092428))^2 + (Z[]-(0.04444999999999055))^2]) * Vector[(Z[]-(0.04444999999999055)), 0, -(X[]-(0.04427401054092428))];
}

