// AUTO-GENERATED by generate_regions.py -- do not hand-edit.
// Region tags and winding current-density sources for the real
// BPL-700 assembly. See build_assembly.py for derivation, this
// file for how excitation-only regeneration works (no remesh).

Group {
  Air = Region[1];
  Iron = Region[2];
  Winding0 = Region[3];
  Winding1 = Region[4];
  Winding2 = Region[5];
  Winding3 = Region[6];
  Winding4 = Region[7];
  OuterBnd = Region[8];
  Windings = Region[{Winding0, Winding1, Winding2, Winding3, Winding4}];
  DomainC  = Region[{Windings}];
  DomainCC = Region[{Air, Iron}];
  Domain   = Region[{DomainC, DomainCC}];
}

Function {
  mu0 = 1.2566370614359173e-06;
  mur_iron = 1000;  // reasonable placeholder (linear) -- see README caveat: soft iron
                    // needs a real nonlinear B-H curve for accuracy near saturation
  nu[Air]  = 1 / mu0;
  nu[Iron] = 1 / (mur_iron * mu0);
  nu[Windings] = 1 / mu0;  // copper, non-magnetic

  // Winding0: pole=outer_solenoid turns=200 I=1.0A A_cross=1.099809e-03 zdir_y=+1 polarity=+1 -> Jmag=1.818498e+05 A/m^2
  Js[Winding0] = (181849.79786551118 / Sqrt[(X[]-(-0.125033506959677))^2 + (Z[]-(0.0770308774188161))^2]) * Vector[(Z[]-(0.0770308774188161)), 0, -(X[]-(-0.125033506959677))];
  // Winding1: pole=outer_solenoid turns=200 I=1.0A A_cross=1.099809e-03 zdir_y=-1 polarity=+1 -> Jmag=-1.818498e+05 A/m^2
  Js[Winding1] = (-181849.79786551118 / Sqrt[(X[]-(0.00196649304032328))^2 + (Z[]-(0.0770308774188161))^2]) * Vector[(Z[]-(0.0770308774188161)), 0, -(X[]-(0.00196649304032328))];
  // Winding2: pole=center_solenoid turns=300 I=0.0A A_cross=1.565348e-03 zdir_y=-1 polarity=-1 -> Jmag=0.000000e+00 A/m^2
  Js[Winding2] = (0.0 / Sqrt[(X[]-(-0.0615335069596768))^2 + (Z[]-(0.0135308774188161))^2]) * Vector[(Z[]-(0.0135308774188161)), 0, -(X[]-(-0.0615335069596768))];
  // Winding3: pole=outer_solenoid turns=200 I=1.0A A_cross=1.099809e-03 zdir_y=-1 polarity=+1 -> Jmag=-1.818498e+05 A/m^2
  Js[Winding3] = (-181849.79786551118 / Sqrt[(X[]-(0.00196649304032332))^2 + (Z[]-(-0.0499691225811839))^2]) * Vector[(Z[]-(-0.0499691225811839)), 0, -(X[]-(0.00196649304032332))];
  // Winding4: pole=outer_solenoid turns=200 I=1.0A A_cross=1.099809e-03 zdir_y=+1 polarity=+1 -> Jmag=1.818498e+05 A/m^2
  Js[Winding4] = (181849.79786551118 / Sqrt[(X[]-(-0.125033506959677))^2 + (Z[]-(-0.0499691225811839))^2]) * Vector[(Z[]-(-0.0499691225811839)), 0, -(X[]-(-0.125033506959677))];
}

