// AUTO-GENERATED by generate_regions.py -- do not hand-edit.
// Region tags, nonlinear iron B-H curve, and winding current-density
// sources for the real BPL-700 assembly. See generate_regions.py for
// derivation.

Group {
  Air = Region[1];
  Iron = Region[2];
  Winding0 = Region[3];
  Winding1 = Region[4];
  Winding2 = Region[5];
  Winding3 = Region[6];
  Winding4 = Region[7];
  OuterBnd = Region[8];
  Windings = Region[{Winding0, Winding1, Winding2, Winding3, Winding4}];
  DomainC  = Region[{Windings}];
  DomainCC = Region[{Air, Iron}];
  Domain   = Region[{DomainC, DomainCC}];
}

Function {
  mu0 = 1.2566370614359173e-06;

  // Generic soft steel B-H curve (GetDP's bundled SteelGeneric material --
  // see this script's module docstring for the exact source/derivation).
  SteelGeneric_H() = {0.0, 5.5023, 11.018, 16.562, 22.149, 27.798, 33.528, 39.363, 45.335, 51.479, 57.842, 64.481, 71.47, 78.906, 86.91, 95.644, 105.32, 116.2, 128.68, 143.22, 160.5, 181.39, 207.11, 239.32, 280.28, 333.14, 402.31, 493.95, 616.78, 783.2, 1011.0, 1325.7, 1764.5, 2381.9, 3257.8, 4511.0, 6318.7, 8947.8, 12802.0, 18500.0, 26989.0, 39739.0, 59047.0, 88520.0, 133880.0, 204250.0, 314340.0, 487960.0, 764030.0};
  SteelGeneric_B() = {0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4};
  SteelGeneric_B2() = SteelGeneric_B()^2;
  SteelGeneric_nu_list() = SteelGeneric_H() / SteelGeneric_B();
  SteelGeneric_nu_list(0) = SteelGeneric_nu_list(1);  // avoid 0/0 at B=0
  SteelGeneric_nu_b2_list() = ListAlt[SteelGeneric_B2(), SteelGeneric_nu_list()];
  SteelGeneric_nu[] = InterpolationLinear[SquNorm[$1]]{SteelGeneric_nu_b2_list()};

  nu[Air]  = 1 / mu0;
  nu[Iron] = SteelGeneric_nu[$1];  // nonlinear -- see magnetostatics_assembly.pro
                                   // for the Vol_L_Mag/Vol_NL_Mag Galerkin split this requires
  nu[Windings] = 1 / mu0;  // copper, non-magnetic

  // Winding0: pole=inner_coil turns=300 I=5.0A A_cross=4.512863e-04 polarity=-1 -> Jmag=-3.323832e+06 A/m^2
  Js[Winding0] = $IFrac * (-3323831.9854989233 / Sqrt[(X[]-(-0.00016711298290286914))^2 + (Z[]-(-6.158486390058627e-16))^2]) * Vector[(Z[]-(-6.158486390058627e-16)), 0, -(X[]-(-0.00016711298290286914))];
  // Winding1: pole=outer_coil turns=200 I=5.0A A_cross=6.333843e-04 polarity=+1 -> Jmag=1.578820e+06 A/m^2
  Js[Winding1] = $IFrac * (1578820.1931119887 / Sqrt[(X[]-(0.04427401054092428))^2 + (Z[]-(-0.044450000000004763))^2]) * Vector[(Z[]-(-0.044450000000004763)), 0, -(X[]-(0.04427401054092428))];
  // Winding2: pole=outer_coil turns=200 I=5.0A A_cross=6.333843e-04 polarity=+1 -> Jmag=1.578820e+06 A/m^2
  Js[Winding2] = $IFrac * (1578820.1931119887 / Sqrt[(X[]-(-0.04462598945906393))^2 + (Z[]-(0.04444999999997634))^2]) * Vector[(Z[]-(0.04444999999997634)), 0, -(X[]-(-0.04462598945906393))];
  // Winding3: pole=outer_coil turns=200 I=5.0A A_cross=6.333843e-04 polarity=+1 -> Jmag=1.578820e+06 A/m^2
  Js[Winding3] = $IFrac * (1578820.1931119887 / Sqrt[(X[]-(-0.04462598945904972))^2 + (Z[]-(-0.04444999999999766))^2]) * Vector[(Z[]-(-0.04444999999999766)), 0, -(X[]-(-0.04462598945904972))];
  // Winding4: pole=outer_coil turns=200 I=5.0A A_cross=6.333843e-04 polarity=+1 -> Jmag=1.578820e+06 A/m^2
  Js[Winding4] = $IFrac * (1578820.1931119887 / Sqrt[(X[]-(0.04427401054092428))^2 + (Z[]-(0.04444999999999055))^2]) * Vector[(Z[]-(0.04444999999999055)), 0, -(X[]-(0.04427401054092428))];
}

