"""
generate_regions.py

Standalone re-generation of assembly_regions_generated.pro for an arbitrary
winding excitation (turns/current/polarity per pole type), WITHOUT
re-running the expensive geometry+meshing step in build_assembly.py. Reads
winding geometry (pole type, A_cross, loc, zdir) from assembly_params.txt,
which build_assembly.py already writes once per mesh.

This is exactly the same Group/Function-block generation as the tail of
build_assembly.py ("Generate the GetDP region/current-source include
file"), just parameterized on an `excitation` dict instead of the
hardcoded EXCITATION constant, and sourced from the params file instead of
in-memory winding_tags/pole_occurrences. magnetostatics_assembly.pro is
untouched -- it just `Include`s whatever this writes.

Used directly by build_assembly.py's own placeholder excitation would
still work (same output), and by current_sweep.py to regenerate the file
per sweep point without remeshing.
"""
import math

from params_utils import parse_params

MU0 = 4 * math.pi * 1e-7

DEFAULT_EXCITATION = {
    "center_solenoid": dict(turns=300, current=5.0, polarity=-1),
    "outer_solenoid":  dict(turns=200, current=5.0, polarity=+1),
}


def generate_regions_pro(params, excitation, out_path="assembly_regions_generated.pro"):
    tag = params["TAG"]
    winding_names = [f"Winding{w['index']}" for w in params["windings"]]

    lines = []
    lines.append("// AUTO-GENERATED by generate_regions.py -- do not hand-edit.")
    lines.append("// Region tags and winding current-density sources for the real")
    lines.append("// BPL-700 assembly. See build_assembly.py for derivation, this")
    lines.append("// file for how excitation-only regeneration works (no remesh).")
    lines.append("")
    lines.append("Group {")
    for name, t in sorted(tag.items(), key=lambda kv: kv[1]):
        lines.append(f"  {name} = Region[{t}];")
    lines.append(f"  Windings = Region[{{{', '.join(winding_names)}}}];")
    lines.append("  DomainC  = Region[{Windings}];")
    lines.append("  DomainCC = Region[{Air, Iron}];")
    lines.append("  Domain   = Region[{DomainC, DomainCC}];")
    lines.append("}")
    lines.append("")
    lines.append("Function {")
    lines.append(f"  mu0 = {MU0!r};")
    lines.append("  mur_iron = 1000;  // reasonable placeholder (linear) -- see README caveat: soft iron")
    lines.append("                    // needs a real nonlinear B-H curve for accuracy near saturation")
    lines.append("  nu[Air]  = 1 / mu0;")
    lines.append("  nu[Iron] = 1 / (mur_iron * mu0);")
    lines.append("  nu[Windings] = 1 / mu0;  // copper, non-magnetic")
    lines.append("")
    for w in params["windings"]:
        i, name, A_cross, loc, zdir = w["index"], w["pole"], w["A_cross"], w["loc"], w["zdir"]
        exc = excitation[name]
        zy = int(round(zdir[1]))
        assert zdir[0] == 0 and zdir[2] == 0 and abs(zy) == 1, \
            f"winding {i} ({name}) local axis isn't along global Y ({zdir}) -- Js[] formula below assumes it is"
        Jmag = exc["polarity"] * zy * exc["turns"] * exc["current"] / A_cross
        lines.append(f"  // Winding{i}: pole={name} turns={exc['turns']} I={exc['current']}A "
                      f"A_cross={A_cross:.6e} zdir_y={zy:+d} polarity={exc['polarity']:+d} -> Jmag={Jmag:.6e} A/m^2")
        lines.append(f"  Js[Winding{i}] = ({Jmag!r} / Sqrt[(X[]-({loc[0]!r}))^2 + (Z[]-({loc[2]!r}))^2]) * "
                      f"Vector[(Z[]-({loc[2]!r})), 0, -(X[]-({loc[0]!r}))];")
    lines.append("}")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    params = parse_params()
    generate_regions_pro(params, DEFAULT_EXCITATION)
    print("Wrote assembly_regions_generated.pro (default placeholder excitation, center 300t/5A vs outer 200t/5A)")
